FROM node:20

# make the 'opt' folder the current working directory
WORKDIR /opt

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY src/client .

# # install project dependencies
RUN npm install

# build app for production with minification
# RUN npm run build

EXPOSE 3000
CMD [ "npm", "run", "serve" ]